### ISSUE TITLE
https://arewewebyet.org doesn't work.

### ISSUE THREAD

**Issue by quadrupleslap** [rust-lang/arewewebyet#155] opened 2019-02-04 19:14 UTC
This is probably the most minor issue ever, but it needs a "www." right now.

**Comment by yoshuawuyts** [comment] 2019-02-11 10:23
@quadrupleslap thanks for the heads up. I agree we should probably fix this!

**Comment by pickfire** [comment] 2019-10-30 16:39
Anything that is blocking this?

**Comment by hugopeixoto** [comment] 2020-10-02 00:38
This issue seems to be a duplicate of https://github.com/rust-lang/arewewebyet/issues/129, which has more info on the status of this. Can this one be closed?

**Comment by ibraheemdev** [comment] 2020-10-15 16:46
tracking in #129

**Closed as completed by ibraheemdev** 2020-10-15 16:46 UTC
