### ISSUE TITLE
Web Framework Addition

### ISSUE THREAD

**Issue by jpoles1** [rust-lang/arewewebyet#105] opened 2018-02-21 15:23 UTC
Might want to add [actix-web](https://github.com/actix/actix-web) to the list of frameworks!

**Comment by ChristophWurst** [comment] 2018-02-21 15:56
Duplicate of https://github.com/bashyHQ/arewewebyet/issues/101, PR in https://github.com/bashyHQ/arewewebyet/pull/104

**Comment by jpoles1** [comment] 2018-02-21 15:58
Sorry for the duplicate!

**Comment by radix** [comment] 2018-03-03 18:18
Done!

**Closed as completed by radix** 2018-03-03 18:18 UTC
