### ISSUE TITLE
Iron is not being maintained at this time

### ISSUE THREAD

**Issue by cybel** [rust-lang/arewewebyet#106] opened 2018-02-26 16:09 UTC
[Recent commit](https://github.com/iron/iron/commit/9e5bccb407b1ec8daef51b0d7494627e5c5fc307#diff-04c6e90faac2675aa89e2176d2eec7d8) says that Iron is not currently being maintained. This may bode poorly for people looking for a well-supported framework. The permanence of this situation is unknown.

**Comment by ChristophWurst** [comment] 2018-02-26 16:16
Duplicate of https://github.com/bashyHQ/arewewebyet/issues/102, I guess.

**Comment by radix** [comment] 2018-03-03 17:12
closing because of duplicate, thanks for the report!

**Closed as completed by radix** 2018-03-03 17:12 UTC
